# Generated by Django 3.2.8 on 2021-11-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=45, null=True)),
                ('emailaddress', models.CharField(max_length=45, null=True, unique=True)),
                ('password', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
    ]
