# Generated by Django 3.2.8 on 2021-11-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers',
            name='state_of_residence',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
