# Generated by Django 3.2.8 on 2021-11-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0002_sellers_state_of_residence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellers',
            old_name='state_of_residence',
            new_name='stateofresidence',
        ),
    ]
