# Generated by Django 3.2.8 on 2021-11-15 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0003_rename_state_of_residence_sellers_stateofresidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sellersID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomerce.sellers')),
            ],
        ),
    ]
