# Generated by Django 3.2.8 on 2021-11-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0004_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='salestatus',
            field=models.BooleanField(default=False),
        ),
    ]
