# Generated by Django 3.2.8 on 2021-11-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0005_products_salestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, null=True)),
                ('lastname', models.CharField(max_length=45, null=True)),
                ('emailaddress', models.CharField(max_length=45, null=True, unique=True)),
                ('password', models.CharField(default='', max_length=250, null=True)),
                ('location', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyersID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomerce.buyers')),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomerce.products')),
                ('sellersID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eccomerce.sellers')),
            ],
        ),
    ]
