# Generated by Django 3.2.8 on 2021-11-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0006_buyers_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderstatus',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
