# Generated by Django 3.2.8 on 2021-11-17 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0007_orders_orderstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='productID',
            new_name='productsID',
        ),
    ]
